// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package schema

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=schema.Status" json:"status,omitempty"`
	Payload              []*Field `protobuf:"bytes,10,rep,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Event) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNACTIVATED
}

func (m *Event) GetPayload() []*Field {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "schema.Event")
}

func init() {
	proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e)
}

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x8a, 0xd4, 0x40,
	0x10, 0xc7, 0xe9, 0x99, 0x35, 0xab, 0xb5, 0x1f, 0x42, 0x7b, 0x30, 0x84, 0x3d, 0x84, 0x08, 0x1a,
	0xd7, 0x35, 0xbd, 0x66, 0x3d, 0x79, 0xdb, 0xf5, 0x0b, 0x45, 0x70, 0x88, 0x88, 0x82, 0x20, 0xf4,
	0x26, 0xc5, 0x6e, 0xc3, 0xa4, 0x3b, 0xa4, 0x7b, 0x02, 0x32, 0xcc, 0xc5, 0x83, 0x2f, 0xe0, 0xab,
	0xf8, 0x26, 0xbe, 0x82, 0x8f, 0xe1, 0x41, 0x52, 0x49, 0x04, 0x0d, 0xc3, 0xec, 0x2d, 0x5d, 0x5d,
	0xf5, 0xfb, 0x55, 0xfe, 0x34, 0xec, 0x60, 0x83, 0xda, 0x25, 0x55, 0x6d, 0x9c, 0xe1, 0x9e, 0xcd,
	0x2f, 0xb1, 0x94, 0xc1, 0xc1, 0x85, 0x31, 0x17, 0x73, 0x14, 0xb2, 0x52, 0x42, 0x6a, 0x6d, 0x9c,
	0x74, 0xca, 0x68, 0xdb, 0x75, 0x05, 0xbb, 0xb9, 0x29, 0x4b, 0xa3, 0xbb, 0x53, 0xf4, 0x8d, 0xc1,
	0xb5, 0xe7, 0x2d, 0x83, 0x73, 0xd8, 0xd2, 0xb2, 0x44, 0x9f, 0x85, 0x2c, 0xbe, 0x91, 0xd1, 0x37,
	0xf7, 0x61, 0xbb, 0xc1, 0xda, 0x2a, 0xa3, 0xfd, 0x09, 0x95, 0x87, 0x23, 0xbf, 0x0b, 0x9e, 0x75,
	0xd2, 0x2d, 0xac, 0x3f, 0x0d, 0x59, 0xbc, 0x9f, 0xee, 0x27, 0x9d, 0x3c, 0x79, 0x47, 0xd5, 0xac,
	0xbf, 0xe5, 0xf7, 0x60, 0xbb, 0x92, 0x5f, 0xe6, 0x46, 0x16, 0x3e, 0x84, 0xd3, 0x78, 0x27, 0xdd,
	0x1b, 0x1a, 0x5f, 0x28, 0x9c, 0x17, 0xd9, 0x70, 0x9b, 0xfe, 0x60, 0xb0, 0x4b, 0x8b, 0x64, 0x28,
	0x8b, 0xd3, 0xd9, 0x2b, 0xfe, 0x1a, 0xb6, 0xde, 0x28, 0xeb, 0xf8, 0xcd, 0x61, 0xe0, 0x6d, 0x45,
	0xbf, 0x11, 0xfc, 0x25, 0x50, 0x7b, 0x14, 0x7e, 0xfd, 0xf9, 0xeb, 0xfb, 0x24, 0xe0, 0xbe, 0xe8,
	0xca, 0x82, 0x22, 0x11, 0xcd, 0xb1, 0x50, 0xda, 0x56, 0x98, 0xbb, 0x63, 0xc6, 0x3f, 0xc2, 0xf4,
	0x25, 0x6e, 0x46, 0x3d, 0x22, 0xd4, 0x03, 0x7e, 0x7f, 0x1d, 0x4a, 0x2c, 0xdb, 0x58, 0x56, 0x62,
	0xd9, 0xc7, 0xb0, 0x4a, 0x7f, 0x4f, 0x60, 0x8f, 0x86, 0x3f, 0xd4, 0xca, 0x61, 0xb7, 0xb7, 0xf7,
	0xb4, 0x46, 0xe9, 0x90, 0xff, 0x4b, 0xff, 0x5f, 0x16, 0x91, 0xec, 0x20, 0xba, 0x3d, 0x92, 0xe5,
	0x34, 0xfe, 0x84, 0x1d, 0xf2, 0x4f, 0xe0, 0xbd, 0xaf, 0x8a, 0xcd, 0xac, 0x13, 0x62, 0x3d, 0x0c,
	0xe2, 0x11, 0x6b, 0x41, 0xe3, 0xa3, 0xbd, 0x5b, 0xf8, 0x67, 0xb8, 0x7e, 0x9a, 0x3b, 0xd5, 0xb4,
	0xf8, 0x4d, 0xc9, 0xa4, 0x24, 0x38, 0x4a, 0x0f, 0x47, 0x02, 0xd9, 0x23, 0x46, 0x0a, 0x7e, 0x0e,
	0xf0, 0x0c, 0xe5, 0x55, 0x0d, 0x8f, 0xc9, 0x90, 0xa4, 0x47, 0x23, 0x43, 0x81, 0x6b, 0x1d, 0x67,
	0x77, 0xe0, 0x56, 0x6e, 0xca, 0xa4, 0xba, 0x54, 0x76, 0xa1, 0x1c, 0xf6, 0xc8, 0x33, 0x20, 0xe6,
	0xac, 0x7d, 0xe1, 0x33, 0x76, 0xee, 0xd1, 0x53, 0x3f, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x17,
	0x43, 0xb4, 0x08, 0x2d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventReadAPIClient is the client API for EventReadAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventReadAPIClient interface {
	List(ctx context.Context, in *Options, opts ...grpc.CallOption) (EventReadAPI_ListClient, error)
	Get(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Event, error)
}

type eventReadAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewEventReadAPIClient(cc grpc.ClientConnInterface) EventReadAPIClient {
	return &eventReadAPIClient{cc}
}

func (c *eventReadAPIClient) List(ctx context.Context, in *Options, opts ...grpc.CallOption) (EventReadAPI_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EventReadAPI_serviceDesc.Streams[0], "/schema.EventReadAPI/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventReadAPIListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventReadAPI_ListClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type eventReadAPIListClient struct {
	grpc.ClientStream
}

func (x *eventReadAPIListClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eventReadAPIClient) Get(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/schema.EventReadAPI/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventReadAPIServer is the server API for EventReadAPI service.
type EventReadAPIServer interface {
	List(*Options, EventReadAPI_ListServer) error
	Get(context.Context, *Options) (*Event, error)
}

// UnimplementedEventReadAPIServer can be embedded to have forward compatible implementations.
type UnimplementedEventReadAPIServer struct {
}

func (*UnimplementedEventReadAPIServer) List(req *Options, srv EventReadAPI_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedEventReadAPIServer) Get(ctx context.Context, req *Options) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterEventReadAPIServer(s *grpc.Server, srv EventReadAPIServer) {
	s.RegisterService(&_EventReadAPI_serviceDesc, srv)
}

func _EventReadAPI_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Options)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventReadAPIServer).List(m, &eventReadAPIListServer{stream})
}

type EventReadAPI_ListServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type eventReadAPIListServer struct {
	grpc.ServerStream
}

func (x *eventReadAPIListServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _EventReadAPI_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Options)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventReadAPIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.EventReadAPI/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventReadAPIServer).Get(ctx, req.(*Options))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventReadAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.EventReadAPI",
	HandlerType: (*EventReadAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _EventReadAPI_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _EventReadAPI_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "event.proto",
}

// EventWriteAPIClient is the client API for EventWriteAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventWriteAPIClient interface {
	Create(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	Update(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	Activate(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Event, error)
	Deactivate(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Event, error)
}

type eventWriteAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewEventWriteAPIClient(cc grpc.ClientConnInterface) EventWriteAPIClient {
	return &eventWriteAPIClient{cc}
}

func (c *eventWriteAPIClient) Create(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/schema.EventWriteAPI/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventWriteAPIClient) Update(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/schema.EventWriteAPI/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventWriteAPIClient) Activate(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/schema.EventWriteAPI/Activate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventWriteAPIClient) Deactivate(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/schema.EventWriteAPI/Deactivate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventWriteAPIServer is the server API for EventWriteAPI service.
type EventWriteAPIServer interface {
	Create(context.Context, *Event) (*Event, error)
	Update(context.Context, *Event) (*Event, error)
	Activate(context.Context, *Options) (*Event, error)
	Deactivate(context.Context, *Options) (*Event, error)
}

// UnimplementedEventWriteAPIServer can be embedded to have forward compatible implementations.
type UnimplementedEventWriteAPIServer struct {
}

func (*UnimplementedEventWriteAPIServer) Create(ctx context.Context, req *Event) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedEventWriteAPIServer) Update(ctx context.Context, req *Event) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedEventWriteAPIServer) Activate(ctx context.Context, req *Options) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Activate not implemented")
}
func (*UnimplementedEventWriteAPIServer) Deactivate(ctx context.Context, req *Options) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deactivate not implemented")
}

func RegisterEventWriteAPIServer(s *grpc.Server, srv EventWriteAPIServer) {
	s.RegisterService(&_EventWriteAPI_serviceDesc, srv)
}

func _EventWriteAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventWriteAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.EventWriteAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventWriteAPIServer).Create(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventWriteAPI_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventWriteAPIServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.EventWriteAPI/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventWriteAPIServer).Update(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventWriteAPI_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Options)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventWriteAPIServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.EventWriteAPI/Activate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventWriteAPIServer).Activate(ctx, req.(*Options))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventWriteAPI_Deactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Options)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventWriteAPIServer).Deactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.EventWriteAPI/Deactivate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventWriteAPIServer).Deactivate(ctx, req.(*Options))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventWriteAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.EventWriteAPI",
	HandlerType: (*EventWriteAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EventWriteAPI_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EventWriteAPI_Update_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _EventWriteAPI_Activate_Handler,
		},
		{
			MethodName: "Deactivate",
			Handler:    _EventWriteAPI_Deactivate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
